veritabaniCRUD2/Controllers/birTabloController.cs
using Microsoft.AspNetCore.Mvc;
using veritabaniCRUD2.Data;
using veritabaniCRUD2.Models;

namespace veritabaniCRUD2.Controllers
{
    public class birTabloController : Controller
    {
        private readonly ApplicationDbContext _context; //kırmızı alt çizgi Ctrl. ile düzelir

        public birTabloController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<birTablo>? _tablo { get; set; }    //kırmızı alt çizgi Ctrl. ile düzelir

        public IActionResult Index(string? aranan = null, string? sirala = null)
        {
            if (aranan != null)
            {
                _tablo = _context.birTablo.Where(x => x.isim.Contains(aranan)).ToList();
                if (_tablo.Count > 0)
                {
                    ViewData["mesaj"] = aranan + ", " + _tablo.Count + " adet bulundu";
                }
                else
                    ViewData["mesaj"] = aranan + " bulunamadı...";
            }
            else
            {
                if (sirala != null)
                {
                    switch (sirala)
                    {
                        case "Id":
                            _tablo = _context.birTablo.OrderBy(x=>x.Id).ToList();
                            ViewData["mesaj"] = "Id ile sıralandı.";
                            break;
                        case "isim":
                            _tablo = _context.birTablo.OrderBy(x => x.isim).ToList();
                            ViewData["mesaj"] = "İsim ile sıralandı.";
                            break;
                        case "ucret":
                            _tablo = _context.birTablo.OrderBy(x => x.ucret).ToList();
                            ViewData["mesaj"] = "Ücret ile sıralandı.";
                            break;
                        default:
                            break;
                    }
                }
                else
                {
                    _tablo = _context.birTablo.ToList();
                    ViewData["mesaj"] = "Aranan kişinin adını giriniz.";
                }
            }

            return View(_tablo.ToList());
        }

        [HttpPost]
        public async Task<IActionResult> Ekle([Bind("Id,isim,ucret")] birTablo tablo)
        {
            _context.Add(tablo);
            await _context.SaveChangesAsync();

            return View(tablo);
        }

        public IActionResult Sil(int? Id = null)
        {
            if (Id != null)
            {

                var tablo = _context.birTablo.Find(Id);
                _context.birTablo.Remove(tablo);
                _context.SaveChanges(); //değişiklikleri kaydeder

                ViewData["mesaj"] = "Silindi";
            }
            else
                ViewData["mesaj"] = "Silinecek kişiyi seçiniz.";
            return View();
        }

        public IActionResult Guncelle(int? Id = null)
        {
            var tablo = _context.birTablo.Find(Id);
            //ViewData["mesaj"] = "Kişi bilgilerini giriniz.";
            return View(tablo);
        }

        [HttpPost]
        public IActionResult Guncelle(int Id, [Bind("Id,isim,ucret")] birTablo birTablo)
        {
            _context.Update(birTablo);
            _context.SaveChangesAsync();
            ViewData["mesaj"] = "Kişi güncellendi.";
            return View(birTablo);
        }
    }
}

veritabaniCRUD2/Controllers/birTabloVerileriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using veritabaniCRUD2.Data;
using veritabaniCRUD2.Models;

namespace veritabaniCRUD2.Controllers
{
    public class birTabloVerileriController : Controller
    {
        private readonly ApplicationDbContext _context;

        public birTabloVerileriController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: birTabloVerileri
        public async Task<IActionResult> Index()
        {
              return _context.birTablo != null ? 
                          View(await _context.birTablo.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.birTablo'  is null.");
        }

        // GET: birTabloVerileri/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.birTablo == null)
            {
                return NotFound();
            }

            var birTablo = await _context.birTablo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (birTablo == null)
            {
                return NotFound();
            }

            return View(birTablo);
        }

        // GET: birTabloVerileri/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: birTabloVerileri/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,isim,ucret")] birTablo birTablo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(birTablo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(birTablo);
        }

        // GET: birTabloVerileri/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.birTablo == null)
            {
                return NotFound();
            }

            var birTablo = await _context.birTablo.FindAsync(id);
            if (birTablo == null)
            {
                return NotFound();
            }
            return View(birTablo);
        }

        // POST: birTabloVerileri/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,isim,ucret")] birTablo birTablo)
        {
            if (id != birTablo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(birTablo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!birTabloExists(birTablo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(birTablo);
        }

        // GET: birTabloVerileri/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.birTablo == null)
            {
                return NotFound();
            }

            var birTablo = await _context.birTablo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (birTablo == null)
            {
                return NotFound();
            }

            return View(birTablo);
        }

        // POST: birTabloVerileri/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.birTablo == null)
            {
                return Problem("Entity set 'ApplicationDbContext.birTablo'  is null.");
            }
            var birTablo = await _context.birTablo.FindAsync(id);
            if (birTablo != null)
            {
                _context.birTablo.Remove(birTablo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool birTabloExists(int id)
        {
          return (_context.birTablo?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

veritabaniCRUD2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - veritabaniCRUD2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/veritabaniCRUD2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">veritabaniCRUD2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="birTabloVerileri" asp-action="Index">birTablo (Hazır)</a>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="birTablo" asp-action="Index">birTablo (Kod ile)</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - veritabaniCRUD2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>